apiVersion: data.clond.com.shalousun/v1
kind: PodSet
metadata:
  name: podset-sample
spec:
  # Add fields here
  replicas: 2
  option: delete
  port: 80
  targetPort: 80
  storageClass: fast-disks
  storageSize: 2Gi
  podLists:
    - 'podset-sample-2'