apiVersion: data.clond.com.shalousun/v1
kind: PodSet
metadata:
  name: podset-sample
spec:
  # Add fields here
  replicas: 3
  option: scale_up
  port: 80
  targetPort: 80
  storageClass: default
  storageSize: 2Gi